// AI Helper — conversation storage + message send
//
// For now, responses are generated by a local content-aware fallback that
// mines the module config for relevant help. When Supabase + Anthropic API
// go live, swap the `askAssistant` stub for a fetch to:
//   POST /functions/v1/ask-assistant  { messages, userContext }
// and the UI stays untouched.

import { SERVICES, type ModuleDef, type ServiceDef } from '../config/modules';
import { db, type AiChatMessage } from './mockDb';

export type ChatMessage = AiChatMessage;

export function loadChatHistory(userId: string): ChatMessage[] {
  if (!userId) return [];
  return db.listAiChatForUser(userId);
}

export function clearChatHistory(userId: string) {
  if (!userId) return;
  db.clearAiChatForUser(userId);
}

export function appendMessage(userId: string, organizationId: string | null, role: 'user' | 'assistant', content: string, context: string | null = null): ChatMessage {
  return db.addAiChatMessage({ userId, organizationId, role, content, context });
}

// ---------- local fallback answer engine ----------

function findRelevantModules(query: string): Array<{ service: ServiceDef; module: ModuleDef; score: number }> {
  const q = query.toLowerCase();
  const hits: Array<{ service: ServiceDef; module: ModuleDef; score: number }> = [];
  const keywords = q.split(/\s+/).filter(w => w.length > 2);

  for (const service of SERVICES) {
    for (const module of service.modules) {
      const haystack = [
        module.title, module.description, module.instructions,
        ...(module.fields ?? []).map(f => `${f.label ?? ''} ${f.helpText ?? ''}`),
      ].join(' ').toLowerCase();

      let score = 0;
      for (const kw of keywords) if (haystack.includes(kw)) score += 1;
      if (module.title.toLowerCase().includes(q)) score += 5;
      if (service.label.toLowerCase().includes(q)) score += 3;

      if (score > 0) hits.push({ service, module, score });
    }
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, 3);
}

function localAnswer(query: string): string {
  const q = query.trim();
  if (!q) return "Ask me anything about completing your onboarding — I'll point you to the right step.";

  const lower = q.toLowerCase();

  if (/^(hi|hello|hey|yo)\b/.test(lower)) {
    return "Hey — I'm your onboarding helper. Ask me things like \"what do I put for unique selling points?\" or \"how do I give you domain access?\" and I'll walk you through it.";
  }

  if (lower.includes('domain') && (lower.includes('access') || lower.includes('delegate') || lower.includes('dns'))) {
    return "For **domain access**, open the Website → Domain access step. You'll pick your registrar (GoDaddy, Namecheap, Cloudflare, or Squarespace) and we'll show a short walkthrough video for your provider. You just need to add **contact@sereniumai.com** with admin or DNS-edit permissions. Takes about 2 minutes.";
  }

  if (lower.includes('analytics') || lower.includes('search console') || lower.includes('gbp') || lower.includes('business profile')) {
    return "For analytics, go to Website → Analytics and tracking access. You'll add **contact@sereniumai.com** to three things: Google Analytics (as Administrator), Google Search Console (as Owner), and Google Business Profile (as Manager). There's a video walkthrough for Google Analytics and linked docs for the others.";
  }

  if (lower.includes('logo') || lower.includes('brand')) {
    return "Under Business Profile → Logo files, upload the highest-resolution version you have (PNG with transparent background is best, SVG if you have it). We use this across your website, ads, and emails. For branding colors and typography, there's a separate Brand and style step in the Website service.";
  }

  if (lower.includes('emergency')) {
    return "Emergency service is in the Business Profile section. If you turn it on, you'll be asked what emergency services you offer, hours, response time, and any extra charges. Flipping this to Yes also unlocks the Emergency Handling steps in AI SMS and AI Receptionist so we know what to do when an emergency lead comes in.";
  }

  if (lower.includes('call forward') || lower.includes('retell') || lower.includes('receptionist')) {
    return "Call forwarding is the last step of AI Receptionist. It stays locked until our team builds your AI agent — once we do, we'll assign you a forwarding number and unlock the step. You'll then pick Option A (forward every call) or Option B (ring your phone first, then forward). The step has dial codes for both iPhone and Android.";
  }

  if (lower.includes('faq') || lower.includes('train') || lower.includes('ai')) {
    return "Training the AI is in AI SMS → Train your AI assistant (and the equivalent in AI Receptionist). You'll add at least 5 FAQs, 3 common objections, the questions you want the AI to collect from every lead (location, roof age, urgency, etc.), and anything the AI should never say. The more specific you are, the more it sounds like you.";
  }

  if (lower.includes('save') || lower.includes('autosave')) {
    return "Everything autosaves as you type — you'll see a 'Saved' indicator at the top of each step. You can safely leave and come back later; your answers stay put.";
  }

  if (lower.includes('time') || lower.includes('how long')) {
    return "Most steps take 2–10 minutes. The full onboarding is usually 2–3 hours spread over however long suits you — you don't have to do it in one sitting. Each step shows its estimated time in the top-right corner.";
  }

  const hits = findRelevantModules(q);
  if (hits.length > 0) {
    const top = hits[0];
    const lines = [`Looks like this relates to **${top.service.label} → ${top.module.title}**.`];
    if (top.module.instructions) lines.push('', top.module.instructions.split('\n')[0]);
    if (hits.length > 1) {
      lines.push('', 'Other steps that might help:');
      for (const h of hits.slice(1)) lines.push(`• ${h.service.label} → ${h.module.title}`);
    }
    return lines.join('\n');
  }

  return "I don't have a direct answer for that yet — but I'll only get smarter as you go. In the meantime, the Serenium team is copied on everything you fill in, so you can drop unclear bits in any field and we'll follow up. You can also email **contact@sereniumai.com** for anything urgent.";
}

// ---------- public API ----------

/**
 * Ask the onboarding assistant a question.
 *
 * Flow:
 *   1. Try the Vercel serverless function /api/ask-assistant (Claude-backed).
 *   2. If that 503s (no API key yet) or network-errors, fall back to the local
 *      keyword-based responder so the chat keeps working in dev / pre-launch.
 */
export async function askAssistant(
  question: string,
  history: Array<{ role: 'user' | 'assistant'; content: string }> = [],
  context: string | null = null,
): Promise<string> {
  try {
    const resp = await fetch('/api/ask-assistant', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ question, history, context }),
    });

    if (resp.ok) {
      const data = (await resp.json()) as { answer?: string };
      if (data.answer) return data.answer;
    }
    // Service unavailable / misconfigured → fall back.
    if (resp.status === 503) return localAnswer(question);
  } catch {
    // Network failure → fall back.
  }

  return localAnswer(question);
}

export const SUGGESTED_QUESTIONS = [
  'How do I give you domain access?',
  'What should I put for unique selling points?',
  'How do I grant Google Analytics access?',
  'Do I need to finish this in one sitting?',
  'How long does the whole onboarding take?',
];
